### ISSUE TITLE
A cancel removes the `[XXX]` tag

### ISSUE THREAD

**Issue by younrx** [RefactorSecurity/vscode-security-notes#10]
Doing `cancel` to discard note message modifications does a removal of the `[XXX]` tag (`XXX` being `Vulnerable`, `Not vulnerable` or `TODO`).
This might be linked to the following submited issue: https://github.com/RefactorSecurity/vscode-security-notes/issues/9

**Comment by ggabarrin** [comment]
Hey @younrx, thanks for reporting this issue as well. 

A quick look at the code suggests that this is not related to #9, but instead related to the `savedBody` property of the `NoteComment` class.

We'll be working a fix shortly. Thank you!

**Comment by ggabarrin** [comment]
Re-opening issue. PR #11 closed issue #9, instead of this one.
