### ISSUE TITLE
Tag `[TODO]` automatically added in new notes

### ISSUE THREAD

**Issue by younrx** [RefactorSecurity/vscode-security-notes#16]
Hello,

I have noticed that when I create a note, the tag `[TODO]` is automatically added. Is this a bug or a whished behavior, since there is a button `Mark as To-Do` to add this tag ? I intuitively consider that no tag should be assigned by default, and only when asked/whished by the user the tags `[TODO]`, `[Vulnerable]` or `[Not Vulnerable]` should be added...

**Comment by ggabarrin** [comment]
Hey @younrx, thanks for submitting this issue. 

Adding the `[TODO]` tag automatically was the intended behavior. However, we've been discussing this behavior internally, and we agree that adding the default tag could be confusing or unnecessary. We'll be removing this behavior.

We'll release a new version shortly with this change. 

Thanks again!
