### ISSUE TITLE
Avoid automatically creating a new security-notes.json

### ISSUE THREAD

**Issue by Kotsuha** [RefactorSecurity/vscode-security-notes#24]
Thanks for this nice local note extension.

It would be nice if it doesn't automatically create a new security-notes.json whenever I open a folder or project in VSCode.

**Comment by ggabarrin** [comment]
Hey @Kotsuha, thanks for submitting this issue and glad to hear you find the extension useful.

Thanks for bringing this up. We agree this current behavior might be a little annoying or cause some inconvenience. 

We'll be working on this as soon as possible.

Thanks!
