### ISSUE TITLE
Deleted comment is still present after vscode restart

### ISSUE THREAD

**Issue by younrx** [RefactorSecurity/vscode-security-notes#6]
Nice idea there! It would be cool to use such a tool. :tada:
I have noticed a few things that I will report on various issues.

This post is about the following problem:

A deleted comment is still present after a vscode restart (any kind of comment. No matter if it is on multiple lines, has replies, emojis, ...)

**Comment by ggabarrin** [comment]
Hey @younrx, thanks for giving the tool a try :) 

Good catch! Deletions were not being persisted properly in the local database. We'll be releasing a fix shortly.

Thanks again!
